import type { CashierInvoice } from "@/interfaces/cashier-invoice";

export const sampleInvoices: CashierInvoice[] = [
  {
    id: "INV001",
    invoiceNumber: "#2024-001",
    tableNumber: "Table 12",
    customerName: "Pradeep Silva",
    type: "dining",
    orders: [
      {
        id: "item1",
        name: "Fish Cutlet",
        quantity: 2,
        unitPrice: 450,
        totalPrice: 900,
      },
      {
        id: "item2", 
        name: "Chicken Curry",
        quantity: 1,
        unitPrice: 850,
        totalPrice: 850,
      },
      {
        id: "item3",
        name: "King Coconut",
        quantity: 2,
        unitPrice: 200,
        totalPrice: 400,
      },
    ],
    subtotal: 2150,
    serviceCharge: 215, // 10%
    discount: 200,
    loyaltyPoints: 21,
    total: 2165,
    createdAt: "2024-01-20T14:30:00Z",
    status: "paid",
  },
  {
    id: "INV002",
    invoiceNumber: "#2024-002",
    customerName: "Kumari Perera",
    type: "takeaway",
    orders: [
      {
        id: "item4",
        name: "Kottu Roti",
        quantity: 1,
        unitPrice: 650,
        totalPrice: 650,
      },
      {
        id: "item5",
        name: "Fish Cutlet",
        quantity: 3,
        unitPrice: 450,
        totalPrice: 1350,
      },
    ],
    subtotal: 2000,
    serviceCharge: 0, // No service charge for takeaway
    discount: 0,
    loyaltyPoints: 20,
    total: 2000,
    createdAt: "2024-01-20T15:45:00Z", 
    status: "paid",
  },
  {
    id: "INV003",
    invoiceNumber: "#2024-003",
    tableNumber: "Table 05",
    customerName: "Thilaka Jayawardena",
    type: "dining",
    orders: [
      {
        id: "item6",
        name: "Chicken Curry",
        quantity: 2,
        unitPrice: 850,
        totalPrice: 1700,
      },
      {
        id: "item7",
        name: "Fish Cutlet", 
        quantity: 1,
        unitPrice: 450,
        totalPrice: 450,
      },
      {
        id: "item8",
        name: "Gotu Kola Salad",
        quantity: 1,
        unitPrice: 380,
        totalPrice: 380,
      },
    ],
    subtotal: 2530,
    serviceCharge: 253,
    discount: 0,
    loyaltyPoints: 25,
    total: 2783,
    createdAt: "2024-01-20T12:15:00Z",
    status: "paid",
  },
  {
    id: "INV004", 
    invoiceNumber: "#2024-004",
    customerName: "Kapila Ranawaka",
    type: "takeaway",
    orders: [
      {
        id: "item9",
        name: "Kottu Roti",
        quantity: 1,
        unitPrice: 650,
        totalPrice: 650,
      },
      {
        id: "item10",
        name: "King Coconut",
        quantity: 1,
        unitPrice: 200,
        totalPrice: 200,
      },
    ],
    subtotal: 850,
    serviceCharge: 0,
    discount: 50, // Small discount applied
    loyaltyPoints: 8,
    total: 800,
    createdAt: "2024-01-20T16:20:00Z",
    status: "paid",
  },
  {
    id: "INV005",
    invoiceNumber: "#2024-005", 
    tableNumber: "Table 08",
    customerName: "Saman Wickramasinghe",
    type: "dining",
    orders: [
      {
        id: "item11",
        name: "Fish Ambul Thiyal",
        quantity: 1,
        unitPrice: 780,
        totalPrice: 780,
      },
      {
        id: "item12",
        name: "String Hoppers",
        quantity: 2,
        unitPrice: 450,
        totalPrice: 900,
      },
      {
        id: "item13",
        name: "Watalappan",
        quantity: 1,
        unitPrice: 320,
        totalPrice: 320,
      },
    ],
    subtotal: 2000,
    serviceCharge: 200,
    discount: 150, // Loyalty discount
    loyaltyPoints: 20,
    total: 2050,
    createdAt: "2024-01-20T18:45:00Z",
    status: "paid",
  },
  {
    id: "INV006",
    invoiceNumber: "#2024-006",
    customerName: "Nimal Fernando",
    type: "takeaway", 
    orders: [
      {
        id: "item14",
        name: "Chicken Curry",
        quantity: 1,
        unitPrice: 850,
        totalPrice: 850,
      },
      {
        id: "item15", 
        name: "Gotu Kola Salad",
        quantity: 1,
        unitPrice: 380,
        totalPrice: 380,
      },
      {
        id: "item16",
        name: "King Coconut",
        quantity: 2,
        unitPrice: 200,
        totalPrice: 400,
      },
    ],
    subtotal: 1630,
    serviceCharge: 0,
    discount: 0,
    loyaltyPoints: 16,
    total: 1630,
    createdAt: "2024-01-20T11:30:00Z",
    status: "paid",
  },
];
